<?php 
   session_start(); 

    include('conexion.php'); 
	
		
?> 


       <div class="posts_l"><a class="post_title"> Galería Reign of Norrath </a>

<div class="post_txt">
<ul id="galeria">
<li class="sec_zoom">
<a href="#" title=""><img class="zoom" alt="" src="URL_de_la_imagen" /><span style="text-decoration:none;">Texto del título o leyenda</span></a>
</li>
<li class="sec_zoom">
<a href="#" title=""><img class="zoom" alt="" src="URL_de_la_imagen" /><span style="text-decoration:none;">Texto del título o leyenda</span></a>
</li>
<li class="sec_zoom">
<a href="#" title=""><img class="zoom" alt="" src="URL_de_la_imagen" /><span style="text-decoration:none;">Texto del título o leyenda</span></a>
</li>
<li class="sec_zoom">
<a href="#" title=""><img class="zoom" alt="" src="URL_de_la_imagen" /><span style="text-decoration:none;">Texto del título o leyenda</span></a>
</li>
<li class="sec_zoom">
<a href="#" title=""><img class="zoom" alt="" src="URL_de_la_imagen" /><span style="text-decoration:none;">Texto del título o leyenda</span></a>
</li>
<li class="sec_zoom">
<a href="#" title=""><img class="zoom" alt="" src="URL_de_la_imagen" /><span style="text-decoration:none;">Texto del título o leyenda</span></a>
</li>

</ul>


</div>
</div>